using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    public static GameManager instance;

    public int month = 1;
    public int day = 1;

    public int playerMoney = 0;        //ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
   
    public int allCreativity; // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ã¢ï¿½ï¿½
    public int allAddictive; // ï¿½ï¿½ï¿½ï¿½ ï¿½ßµï¿½ï¿½ï¿½
    public int allMelodic; // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Îµï¿½ï¿½ï¿?
    public int allPopularity; // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ß¼ï¿½

    public int curBPM = 100;

    void Start()
    {
        if(instance == null)
        {
            instance = this;
            DontDestroyOnLoad(this.gameObject);
        }
        else
        {
            Debug.Log("ï¿½Ì¹ï¿½ ï¿½ï¿½ï¿½Ó¸Å´ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Õ´Ï´ï¿½.");
        }
        
        UIManager.instance?.GameStart();
        StartCoroutine(DayTimer()); 
    }


    IEnumerator DayTimer()
    {
        if (month != 12)
        {

            yield return new WaitForSeconds(120f);
            if (day != 31)
            {
                day++;
                UIManager.instance.CalendarSetting();
            }
            else
            {
                month++;
                day = 1;
                UIManager.instance.CalendarSetting();
            }
            StartCoroutine(DayTimer());

        }
    }

    // Update is called once per frame
    void Update()
    {

    }

}
